[tool.poetry]
name = "latexdl"
version = "0.1.0"
description = ""
authors = ["Nima Shoghi <nimashoghi@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7"
arxiv = "^2.1.0"
tqdm = "^4.66.4"
requests = "*"
texsoup = "^0.3.1"


[tool.poetry.group.dev.dependencies]
ipykernel = "*"
rich = "*"
ruff = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
latexdl = "latexdl:main"
